// 9-11-2024/vue/tres-ejemplos-vue/src/App.vue
<template>
    <div id="app">
      <Contador />
      <MostrarOcultar />
      <DetectarMouse />
    </div>
  </template>
  
  <script>
  import Contador from './components/Contador.vue';
  import MostrarOcultar from './components/MostrarOcultar.vue';
  import DetectarMouse from './components/DetectarMouse.vue';
  
  export default {
    name: 'App',
    components: {
      Contador,
      MostrarOcultar,
      DetectarMouse,
    },
  };
  </script>

// 9-11-2024/react/tres-ejemplos/src/App.js
import logo from './logo.svg';
import './App.css';
import Contador from './componentes/boton';
import MostrarOcultar from './componentes/MostrarOcultar';
import DetectarMouse from './componentes/DetectarMouse';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <Contador></Contador>
        <MostrarOcultar></MostrarOcultar>
        <DetectarMouse></DetectarMouse>
      </header>
    </div>
  );
}

export default App;
