// 9-11-2024/react/tres-ejemplos/src/componentes/DetectarMouse.js
import React, { useState } from 'react';

function DetectarMouse() {
  const manejarMouse = () => {
    alert("Se detectó el evento");
  };

  return (
    <div>
      <p 
        onMouseEnter={manejarMouse}
        style={{ cursor: 'pointer' }}
      >
        Pasa el mouse por encima
      </p>
    </div>
  );
}

export default DetectarMouse;

// 9-11-2024/vue/tres-ejemplos-vue/src/components/DetectarMouse.vue
<template>
    <div>
      <p @mouseenter="mostrarAlerta" style="cursor: pointer;">
        Pasa el mouse por encima
      </p>
    </div>
  </template>
  
  <script>
  export default {
    name: 'DetectarMouse',
    methods: {
      mostrarAlerta() {
        alert('Se detectó el evento');
      },
    },
  };
  </script>
