// 9-11-2024/react/tres-ejemplos/src/componentes/MostrarOcultar.js
import React, { useState } from 'react';

function MostrarOcultar() {
  const [mostrar, setMostrar] = useState(false); // Inicializa el estado 'mostrar' como false (oculto)

  return (
    <div>
      <button onClick={() => setMostrar(!mostrar)}>
        {mostrar ? 'Ocultar' : 'Mostrar'} Texto
      </button>
      {mostrar && <p>Este es el texto que se muestra u oculta.</p>}
    </div>
  );
}

export default MostrarOcultar;

// 9-11-2024/vue/tres-ejemplos-vue/src/components/MostrarOcultar.vue
<template>
    <div>
      <button @click="mostrar = !mostrar">
        {{ mostrar ? 'Ocultar' : 'Mostrar' }} Texto
      </button>
      <p v-if="mostrar">Este es el texto que se muestra u oculta.</p>
    </div>
  </template>
  
  <script>
  export default {
    name: 'MostrarOcultar',
    data() {
      return {
        mostrar: false, // Inicialmente el texto está oculto
      };
    },
  };
  </script>
